model_list:
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro
      api_key: ${GEMINI_API_KEY}

litellm_settings:
  drop_params: True
  num_retries: 3
  routing_strategy: simple-shuffle
  allowed_fails: 1