model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: ${OPENAI_API_KEY}

litellm_settings:
  drop_params: True
  num_retries: 3
  routing_strategy: simple-shuffle
  allowed_fails: 1