model_list:
  # Anthropic models
  - model_name: claude-3-5-sonnet 
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      
  - model_name: claude-3-5-sonnet-20240620
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
      
  - model_name: claude-3-7-sonnet
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219

  # OpenAI models
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o

  # Gemini models
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro

environment_variables:
  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  GEMINI_API_KEY: ${GEMINI_API_KEY}
  
litellm_settings:
  drop_params: True
  num_retries: 3
  routing_strategy: simple-shuffle
  allowed_fails: 1