# This file will be generated by 'nixos-generate-config' when setting up the actual hardware
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Placeholder configuration - replace with actual hardware config when deploying
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
