[whitelist]
prefix = ["/Users/ade-sede/alan/workspace-5", "/Users/ade-sede/alan/alan-apps", "/Users/ade-sede/alan/workspace-4", "/Users/ade-sede/alan/workspace-2", "/Users/ade-sede/alan/workspace-3"]
