model: gemini-2.0-flash
provider: gemini

providers:
  anthropic:
    name: Anthropic
    baseURL: https://api.anthropic.com/v1
    envKey: ANTHROPIC_API_KEY
  
  openai:
    name: OpenAI
    baseURL: https://api.openai.com/v1
    envKey: OPENAI_API_KEY
  
  gemini:
    name: Gemini
    baseURL: https://generativelanguage.googleapis.com/v1beta/openai
    envKey: GEMINI_API_KEY
  
  litellm:
    name: LiteLLM Proxy
    baseURL: http://localhost:4000/v1
    envKey: FAKE_LITELLM_KEY

ignorePatterns:
  - "node_modules"
  - ".git"
  - "dist"
  - "build"
  - "__pycache__"
