model: gemini-2.5-pro-preview-03-25
provider: gemini
providers:
  openai:
    name: OpenAI
    baseURL: https://api.openai.com/v1
    envKey: OPENAI_API_KEY
    name: Gemini
    baseURL: https://generativelanguage.googleapis.com/v1beta/openai
    envKey: GEMINI_API_KEY
  anthropic:
    name: Anthropic
    baseURL: https://api.anthropic.com/v1
    envKey: ANTHROPIC_API_KEY
  litellm:
    name: LiteLLM Proxy
    baseURL: http://localhost:4000/v1
    envKey: FAKE_LITELLM_KEY
history:
  maxSize: 1000
  saveHistory: true
  sensitivePatterns: []
